### ISSUE TITLE
What We'll Make - Stylised Personal Site

### ISSUE THREAD

**Issue by Baktygul-kk** [movers-kelechek/Intermediate-CSS#1]
1. Объяснить тему,
2. Привести пример

**Comment by bekmyrzazhakshylykuulu** [comment]
[css.zip](https://github.com/movers-kelechek/Intermediate-CSS/files/6951069/css.zip)
Бул сабак абдан түшүнүктүү болду. Мурдагы сабактарга караганда видеосун тартуу да бир аз жеңил болду.
Жалпысынан 1 сааттай убакыт короттум.
