### ISSUE TITLE
The Dark Art of Centering Elements with CSS

### ISSUE THREAD

**Issue by Baktygul-kk** [movers-kelechek/Intermediate-CSS#8]
1. Объяснить тему.
2. Привести примеры
3. Оставить ссылки на полезные ресурсы

**Comment by kanyshaiosmonova** [comment]
[the dark art of centering elements with css.zip](https://github.com/movers-kelechek/CSS---Intermediate/files/6946625/the.dark.art.of.centering.elements.with.css.zip)

**Comment by kanyshaiosmonova** [comment]
На это задание у меня ушло 5 часов. Было сложно. Я пересматривала снова и снова. И предыдущие все уроки посмотрела. Искала информацию в интернете.
