### ISSUE TITLE
Font Styling in Our Personal Site

### ISSUE THREAD

**Issue by Baktygul-kk** [movers-kelechek/Intermediate-CSS#9]
1. Объяснить тему
2. Привести пример
3. Оставить ссылки на полезные ресурсы

**Comment by kanyshaiosmonova** [comment]
[https://youtu.be/neCLNHy6xaU](url) Youtube link of the video
[CSS- My Site.zip](https://github.com/movers-kelechek/CSS---Intermediate/files/6946553/CSS-.My.Site.zip)

**Comment by kanyshaiosmonova** [comment]
На это у меня ушло 2 часа. Много чему научилась.
